### ISSUE TITLE
Generieke aanpassingen in rapporten

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#219]
## Todo
- [x] wegwerken "Brussel twee keer vergelijkingsgebied als je een Brusselse gemeente kiest" (zie https://github.com/provinciesincijfers/PinC-taakopvolging/issues/201#issuecomment-797372475 ; enkel in Rapporten waar Brussel effectief gekozen kan worden nodig!)
`if count_compare=2 AND Equal(name(item(input_compare,0)), "Brussels Hoofdstedelijk Gewest") then
input_compare=Parent(item(input_compare,0), gewest)
count_compare=1
end if`
(toegevoegd op regel 90 van sjabloon_rapport_vertrekproject)
- [x] In rapporten waar er bewust voor een vast beginjaar gekozen wordt, kan je evolutiegrafieken toch automatisch laten bijwerken. Codevoorbeeld lijn_beginjaar2010 in sjabloon_grafiekstijl.
- [x] nakijken gebruik jaartallen in titels en bij samenstelling van grafieken. Zie "Technische regels ivm verwijzing naar jaartal" in sjabloon_grafiekstijl. Zie ook de code van lijn_10jaar. Waar gewerkt wordt met vaste jaren in lijngrafieken, nagaan bij verantwoordelijke of dit een bewuste keuze is (en de reeksen dus elk jaar langer mogen worden)
- [ ] door de bestaande rapporten gaan en slecht gedocumenteerde code aanduiden met `<!-- todo-documenteren -->`, en eventueel overnemen in sjabloon
- [x] in rapporten op provincieniveau de kaarten steeds uitsplisten naar gemeente (ook bij meerdere gekozen provincies). Werkt nu reeds zo in sjabloon_grafiekstijl. In sommige rapporten zie je nog een kaartje op provincieniveau
- [x] Aanpassen leeswijzer zoals hieronder uitgelegd (zie https://github.com/provinciesincijfers/PinC-taakopvolging/issues/239), maar dat kan pas eens standaard overzicht gebruikte bronnen voor tabel aan einde van elke inhoudelijke rapporten klaar is (zie https://github.com/provinciesincijfers/PinC-taakopvolging/issues/235)

## Wontfix
- [x] als je Brussel als Provincie kiest, wordt vergeleken met Brussel het Gewest (en dat kan een gebruiker niet overrulen) (low prior) (zie https://github.com/provinciesincijfers/PinC-taakopvolging/issues/201#issuecomment-797372475) > onoplosbaar
- [x] overal waar een gebiedsniveau wordt gedefinieerd, dit vooraf laten gaan door "geo." > sjabloon instructie zo steeds doorvoeren: de moeite niet in verhouding tot de hoeveelheid werk (en kans op fouten). Enkel vanaf nu steeds doen bij nieuwe en volledig herwerkte rapporten

**Comment by joostschouppe** [comment]
Voorstel maken voor standaard overzicht gebruikte bronnen voor tabel aan einde van elke inhoudelijke rapporten.

**Comment by joostschouppe** [comment]
Voor toevoeging aan leeswijzer, beetje herschreven:

![afbeelding](https://user-images.githubusercontent.com/10122639/129705692-6668ecce-fe9b-435b-9458-d82c41abf209.png)

**Comment by joostschouppe** [comment]
Voorstel Bronnenoverzicht klaargezet

**Comment by joostschouppe** [comment]
Is dit oplosbaar? Indien Vlaamse+Brusselse gemeenten: je kan geen vergelijkingsgebied selecteren. Kies je als bijkomende gemeente Aalst dan wordt er automatisch vergeleken met "Centrale gemeenten; grote of regionale stad". Kies je voor Aalter dan wordt er vergeleken met: "Andere gemeenten; buiten stadsgewest; zeer goed uitgerust"

**Comment by VickyVB** [comment]
Er zijn pas cijfers vanaf 2010, dus wanneer ik schrijf 20 jaar, bedoel ik eigenlijk: neem alles. Maar als index heb ik steeds per._2010 gedefinieerd en in de tekst in dat geval ook gewoon '2010' geschreven. Ik houd het in het achterhoofd voor wanneer het rapport eens een grote make-over krijgt.

**Comment by Lievendr** [comment]
2 lijngrafieken in Landbouw aangepast

**Comment by joostschouppe** [comment]
@davidcardinaels RE https://github.com/provinciesincijfers/PinC-taakopvolging/issues/219#issuecomment-959180342 , dat lijkt me inderdaad niet op te lossen zonder meerdere versies van de hele HTML tabel te maken. En dat lijkt me onwenselijk. We laten het dus gewoon zo.

**Comment by joostschouppe** [comment]
Als er gebruik wordt gemaakt van block-left / block-right, dan is afgesproken dat de breedte van de figuur 400 moet zijn. In Rapport Klimaat bleek dit 410 te zijn. En dat bleek ertoe te leiden dat de export naar PDF een beetje lelijker was dan nodig. We moeten daarom in alle rapporten even de breedte van de figuren checken.
Ik heb dit snel aangepast in alle rapporten. In bijlage de toestand voorheen, voor in het geval dat er toch ergens een reden was om afwijkende getallen te gebruiken
[Report_637801076480546230.zip](https://github.com/provinciesincijfers/PinC-taakopvolging/files/8042454/Report_637801076480546230.zip)
.
