### ISSUE TITLE
Kleine generieke taakjes in Rapporten

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/PinC-taakopvolging#4]
Gemakkelijke kleine dingen die in alle rapporten moeten gebeuren:
- [x] met uitzondering van project_ links, alle rapport-doorverwijzingen niet van type https://provincies.incijfers.be/databank?report= maar van type https://provincies.incijfers.be/jive/report/?id=
- [x] "ShowGeoCompareGeolevelName" False "ShowGeoCompareGeolevelName" toegevoegd in alle online rapporten: zorgt ervoor dat er in tabellen, kaarten en grafieken niet _"gewest" Vlaams Gewest_ verschijnt
- [ ] verwijderen van overbodige #Write(name(level(item(input_geo,0))))# in teksten van rapporten: anders verschijnt er overal "gemeente" X of "provincie" Y. Volstaat om dit éénmalig in het begin van het rapport (inleiding of inhoud) te vermelden.
- [x] titel van het rapport zoals in het Sjabloon
- [x] vertel Swing dat je niet naar je tabellen wil bellen: `<meta name="format-detection" content="telephone=no"/>`
- [x] printen niet toestaan, standaard marges PDF: (bovenaan rapport) `
SetNoPrinting()
SetPDFMargins(0.95, 1.5, 1, 1)
`
- [ ] standaard structuur van "begin van het rapport" (nu https://github.com/provinciesincijfers/PinC-taakopvolging/issues/26 afgerond is)
- [x] inputs zoveel mogelijk zelfde benaming (voor zover [logica 1-veel/2](https://github.com/provinciesincijfers/PinC-taakopvolging/issues/2) is doorgevoerd
- [x] body van het rapport zit goed: begint en eindigt met lege div
- [x] alle links naar Databank die Swing Parameters bevat heeft een keepworkspace=true
- [x] nakijken of er ongebruikte presentaties zijn
- [x] zoveel mogelijk wegwerken verwijzen naar specifiek grafieknummer in de tekst (aangezien bij automatische nummering je niet kan rekenen dat dit nummer gelijk blijft) / of beter nog: gebruik de logica van hoofdstuk 1.3 in sjabloon_rapport
- [ ] foto's invoegen (conditioneel aan [taak 5](https://github.com/provinciesincijfers/PinC-taakopvolging/issues/5) en bij gelegenheid daarvan de eerste pagina uniformiseren (zie sjabloon)
- [ ] is de inhoudstafel in orde (zie sjabloon) - @StefanJacques
- [ ] figuurtitels: automatische nummering in orde brengen + titels harmoniseren - @StefanJacques
- [ ] figuurtitels en hoofdstuktitels: nakijken of er "de gekozen gebieden" komt te staan i.p.v. opsomming van de gebieden
- [ ] belangrijke kaarten en alle figuren interactief maken - @StefanJacques
- [ ] slecht gedocumenteerde code aanduiden met `<!-- todo-documenteren -->`
- [ ] toevoegen "link terug naar begin van rapport" in stijl van sjabloon - @StefanJacques

**Comment by StefanJacques** [comment]
alle rapport-doorverwijzingen niet van type https://provincies.incijfers.be/databank?report= maar **van type https://provincies.incijfers.be/jive/report/?id=**
gebeurd voor:

- kerncijfers
- steekkaart demografie
- cijfers economie opgelijst
- rapport detailhandel
- rapport wonen
- rapport armoede
- rapport klimaat
- rapport onderwijs
- rapport ouderenzorg
- rapport veiligheid

zoveel "verkeerde" verwijzingen zaten eer niet meer in, hoor.

**Comment by StefanJacques** [comment]
titel van het rapport zoals in het Sjabloon
@joostschouppe : jij had het sjabloon al hiernaar aangepast - ik heb alle online rapporten, steekkaarten, ... conform het 'nieuwe' sjabloon gemaakt

**Comment by joostschouppe** [comment]
Openstaande taken gemigreerd naar https://github.com/provinciesincijfers/PinC-taakopvolging/issues/49
